services:
  postgresql:
    image: bitnami/postgresql:15
    restart: always
    ports:
      - "15432:5432"
    env_file:
      - .env

  mysql:
    image: bitnami/mysql:8.0
    restart: always
    ports:
      - "13306:3306"
    env_file:
      - .env
